name: joeltd
favicon: null
layout_spectrum: 0.9267506028991193
typography_spectrum: 0.5338548889849335
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.18970230920240283
  lightness: 0.48699926817789674
  saturation: 0.7161428157705814
  rhythmicContrast: 0.17565312050282955
purpose: []
